### ISSUE TITLE
Headings padded with spaces

### ISSUE THREAD

**Issue by maacl** [relevance/org-html-slideshow#1]
Headings cf. the example.html appears to be padded with 3 non-breaking spaces. The spaces are introduced by the org-mode html export to create distance between the headline and the tag(s). The challenge is that the spaces mess up positioning (alignment) of the headlines. As far as I can tell the insertion of spaces is not something that can be easily tweaked in org-mode.

**Comment by stuartsierra** [comment]
Yes. The extra spaces could be fixed in the ClojureScript code by manipulating the DOM. Patches welcome.

**Comment by maacl** [comment]
Ok, I will attempt a patch.

On Sat, Mar 10, 2012 at 7:03 PM, Stuart Sierra <
reply@reply.github.com

**Comment by jblomo** [comment]
I think this issue is resolved.  @stuartsierra added `remove-heading-spaces` in c3367a41

**Comment by stuartsierra** [comment]
Already fixed.
