### ISSUE TITLE
publishing to web?

### ISSUE THREAD

**Issue by jaydixit** [relevance/org-html-slideshow#16]
Have you had success publishing org-html-slideshow presentations to the web? 

It seems like figuring out how to automatically upload images, CSS files, and other local assets could get complicated. Do you have any thoughts about how to do this?

**Comment by jblomo** [comment]
I publish slides to the web in two ways:

1) using Github's `gh-pages` branch functionality.  For example, see my set of slides from a class I teach: http://jblomo.github.io/datamining290/ .

2) Copying a directory to an S3 path. Usually I will keep my slides in revision control, so the command to copy to s3 is `s3cmd sync -P --exclude='*.git*' slidedeck s3://my-bucket/` .  The advantages of this method are more flexibility in what you upload (eg larger media files), no indexing by google, ability to change permissions.

**Comment by stuartsierra** [comment]
I developed org-html-slideshow for in-person presentations only. I never even tested for compatibility with any browsers other than Google Chrome.
