### ISSUE TITLE
Refresh browser resets display from slide presentation view back to "structure" view

### ISSUE THREAD

**Issue by robstewart57** [relevance/org-html-slideshow#18]
If I modify the org file, then do `C-c C-e h h` then hit refresh in my web browser, I am returned to the structure view of the presentation. I then have to hit `t` on my keyboard to go back to the slide presentation view. If I want to edit the contents of slide 50 then see the changes, AFAIK I hit `C-c C-e h h` then refresh my browser, then hit `t`, then the right arrow on my keyboard 50 times to return to the modified file.

Is there a more efficient work flow for modifying files and viewing the slide in the browser?

**Comment by dchelimsky** [comment]
I'm actually having a different experience. Every time I forward through the slides, the URL changes from e.g. file:///path/to/my/slides.html#slide-id-1 to file:///path/to/my/slides.html#slide-id-2, etc. When I refresh the browser, the URL does not change. Yes, the view is now the structure view, but hitting `t` gets me back to where I was. What are we doing differently?

**Comment by robstewart57** [comment]
Actually, you're absolutely right, I see the same behaviour. Thanks for rehearsing this through with me. The issue I reported doesn't appear to be an issue at all.

**Comment by dchelimsky** [comment]
You're welcome. Happy to help.
