### ISSUE TITLE
using googleVis?

### ISSUE THREAD

**Issue by gtuckerkellogg** [relevance/org-html-slideshow#6]
I noticed a nice use of knitr to create interactive slide presentations with googleVis and R on http://lamages.blogspot.com/2012/05/interactive-html-presentation-with-r.html.  My first thought was to do this in org using org-html-slideshow, and a simple attempt is at the gist https://gist.github.com/2841582 .  (note that I've included the googleVis org-babel output, so you can see the results by exporting the org file even if you don't have the R packages).  The issue is that while the normal R graphics work fine, the googleVis graphics do not display when I toggle to slideshow mode.  Is this my issue, or is this a limitation of org-html-slideshow?

(I know the doc says to move the javascript to the end, but it doesn't seem to work in that case either)

**Comment by stuartsierra** [comment]
Gist has been deleted and I don't understand the request.
